import { test, expect } from '@playwright/test';

test('perfil y favoritos persisten desde navegador con backend y PostgreSQL reales', async ({ page }) => {
  const api = process.env.LIVE_API_URL;
  if (!api) throw new Error('Run infra/verify-profile-browser.ps1 with the isolated backend.');
  await page.goto('/login');
  await page.getByLabel('Correo electrónico').fill('estudiante@duoc.cl');
  await page.getByLabel('Contraseña', { exact: true }).fill('admin123');
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click();
  await expect(page).not.toHaveURL(/\/login$/);
  const token = await page.evaluate(() => localStorage.getItem('token'));
  expect(token).toBeTruthy();
  const headers = { Authorization: `Bearer ${token}` };
  await page.goto('/perfil');
  await page.getByLabel('RSH (%)').fill('0');
  await page.getByLabel('NEM Promedio').fill('5.5');
  await page.getByLabel('Región', { exact: true }).selectOption('1');
  await page.getByLabel('Institución', { exact: true }).selectOption('1');
  await page.getByLabel('Carrera de Interés').fill('Educación en Ñuble');
  await page.getByRole('button', { name: 'Guardar Perfil' }).click();
  await expect(page.getByRole('status')).toContainText('Perfil guardado');
  await page.reload();
  await expect(page.getByLabel('RSH (%)')).toHaveValue('0');
  await expect(page.getByLabel('NEM Promedio')).toHaveValue('5.5');
  await expect(page.getByLabel('Carrera de Interés')).toHaveValue('Educación en Ñuble');
  let response = await page.request.get(`${api}/api/perfil`, { headers });
  expect(response.status()).toBe(200);
  expect((await response.json()).data).toMatchObject({ rshPorcentaje: 0, nemPromedio: 5.5, carreraInteres: 'Educación en Ñuble' });
  await page.getByLabel('Región', { exact: true }).selectOption('');
  await page.getByLabel('Institución', { exact: true }).selectOption('');
  await page.getByLabel('Carrera de Interés').fill('');
  await page.getByRole('button', { name: 'Guardar Perfil' }).click();
  await expect(page.getByRole('status')).toContainText('Perfil guardado');
  await page.reload();
  await expect(page.getByLabel('Región', { exact: true })).toHaveValue('');
  await expect(page.getByLabel('Institución', { exact: true })).toHaveValue('');
  await expect(page.getByLabel('Carrera de Interés')).toHaveValue('');
  await page.getByRole('link', { name: 'Ver recomendaciones con mi perfil guardado' }).click();
  await expect(page).toHaveURL(/mode=recomendar/);
  await expect(page.getByRole('button', { name: 'Guardar en favoritos' }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Guardar en favoritos' }).first().click();
  await expect(page.getByRole('button', { name: 'Quitar de favoritos' }).first()).toBeEnabled();
  await page.goto('/favoritos');
  await expect(page.getByRole('button', { name: 'Quitar de favoritos' })).toHaveCount(1);
  await page.reload();
  await expect(page.getByRole('button', { name: 'Quitar de favoritos' })).toHaveCount(1);
  response = await page.request.get(`${api}/api/favoritos`, { headers });
  expect(response.status()).toBe(200);
  expect((await response.json()).data).toHaveLength(1);
  await page.getByRole('button', { name: 'Quitar de favoritos' }).click();
  await expect(page.getByRole('heading', { name: 'No tienes becas guardadas' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'No tienes becas guardadas' })).toBeVisible();
  response = await page.request.get(`${api}/api/favoritos`, { headers });
  expect((await response.json()).data).toHaveLength(0);
});
