-- =============================================
-- BecasFind - DDL completo - PostgreSQL 18
-- =============================================
BEGIN;

-- =============================================
-- Tabla: regiones
-- =============================================
CREATE TABLE IF NOT EXISTS regiones (
    id_region BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    abreviatura VARCHAR(10) NOT NULL
);

-- =============================================
-- Tabla: comunas
-- =============================================
CREATE TABLE IF NOT EXISTS comunas (
    id_comuna BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_region BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT fk_comuna_region
        FOREIGN KEY (id_region) REFERENCES regiones(id_region)
);

CREATE INDEX IF NOT EXISTS idx_comuna_region
    ON comunas(id_region);

-- =============================================
-- Tabla: roles
-- =============================================
CREATE TABLE IF NOT EXISTS roles (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(50) NOT NULL UNIQUE
);

-- =============================================
-- Tabla: usuarios
-- Soft delete mediante activo (TRUE = activo, FALSE = eliminado)
-- =============================================
CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nombre_completo VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol) REFERENCES roles(id_rol)
);

CREATE INDEX IF NOT EXISTS idx_usuario_email
    ON usuarios(email);

CREATE INDEX IF NOT EXISTS idx_usuario_activo
    ON usuarios(activo);

-- =============================================
-- Tabla: tipos_institucion
-- =============================================
CREATE TABLE IF NOT EXISTS tipos_institucion (
    id_tipo_inst BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

-- =============================================
-- Tabla: instituciones
-- =============================================
CREATE TABLE IF NOT EXISTS instituciones (
    id_institucion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_inst BIGINT NOT NULL,
    rut VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    sitio_web VARCHAR(255),
    contacto_email VARCHAR(255),
    CONSTRAINT fk_institucion_tipo
        FOREIGN KEY (id_tipo_inst) REFERENCES tipos_institucion(id_tipo_inst)
);

CREATE INDEX IF NOT EXISTS idx_institucion_tipo
    ON instituciones(id_tipo_inst);

-- =============================================
-- Tabla: tipos_beca
-- =============================================
CREATE TABLE IF NOT EXISTS tipos_beca (
    id_tipo_beca BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

-- =============================================
-- Tabla: becas (entidad central)
-- =============================================
CREATE TABLE IF NOT EXISTS becas (
    id_beca BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_institucion BIGINT NOT NULL,
    id_tipo_beca BIGINT NOT NULL,
    id_usuario_creador BIGINT NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    descripcion_corta TEXT,
    descripcion_larga TEXT,
    monto_cobertura VARCHAR(255),
    fecha_inicio_postulacion DATE,
    fecha_cierre_postulacion DATE NOT NULL,
    url_oficial VARCHAR(500),
    estado_activa BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_beca_institucion
        FOREIGN KEY (id_institucion) REFERENCES instituciones(id_institucion),
    CONSTRAINT fk_beca_tipo
        FOREIGN KEY (id_tipo_beca) REFERENCES tipos_beca(id_tipo_beca),
    CONSTRAINT fk_beca_usuario
        FOREIGN KEY (id_usuario_creador) REFERENCES usuarios(id_usuario)
);

CREATE INDEX IF NOT EXISTS idx_beca_institucion
    ON becas(id_institucion);

CREATE INDEX IF NOT EXISTS idx_beca_tipo
    ON becas(id_tipo_beca);

CREATE INDEX IF NOT EXISTS idx_beca_estado
    ON becas(estado_activa);

CREATE INDEX IF NOT EXISTS idx_beca_fecha_cierre
    ON becas(fecha_cierre_postulacion);

CREATE INDEX IF NOT EXISTS idx_beca_vigencia
    ON becas(estado_activa, fecha_cierre_postulacion);

-- =============================================
-- Tabla: becas_regiones (relacion M:N Beca-Region)
-- =============================================
CREATE TABLE IF NOT EXISTS becas_regiones (
    id_beca BIGINT NOT NULL,
    id_region BIGINT NOT NULL,
    PRIMARY KEY (id_beca, id_region),
    CONSTRAINT fk_br_beca
        FOREIGN KEY (id_beca) REFERENCES becas(id_beca) ON DELETE CASCADE,
    CONSTRAINT fk_br_region
        FOREIGN KEY (id_region) REFERENCES regiones(id_region) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_br_region
    ON becas_regiones(id_region);

-- =============================================
-- Tabla: requisitos_perfil (relacion 1:1 con Beca)
-- =============================================
CREATE TABLE IF NOT EXISTS requisitos_perfil (
    id_requisito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_beca BIGINT NOT NULL UNIQUE,
    rsh_maximo_porcentaje INTEGER,
    nem_minimo NUMERIC(3,1),
    paes_minimo INTEGER,
    es_para_primer_anio BOOLEAN NOT NULL DEFAULT FALSE,
    es_para_curso_superior BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_rp_beca
        FOREIGN KEY (id_beca) REFERENCES becas(id_beca) ON DELETE CASCADE
);

-- =============================================
-- Tabla: documentos_requeridos (relacion N:1 con Beca)
-- =============================================
CREATE TABLE IF NOT EXISTS documentos_requeridos (
    id_documento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_beca BIGINT NOT NULL,
    nombre_documento VARCHAR(255) NOT NULL,
    es_obligatorio BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_dr_beca
        FOREIGN KEY (id_beca) REFERENCES becas(id_beca) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_dr_beca
    ON documentos_requeridos(id_beca);

-- =============================================
-- Tabla: password_reset_tokens
-- Token UUID con expiracion de 15 minutos
-- =============================================
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token UUID NOT NULL,
    id_usuario BIGINT NOT NULL,
    fecha_expiracion TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_prt_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_prt_token
    ON password_reset_tokens(token);

CREATE INDEX IF NOT EXISTS idx_prt_usuario
    ON password_reset_tokens(id_usuario);

-- =============================================
-- Tabla: perfiles_estudiante (relacion 1:1 con Usuario)
-- =============================================
CREATE TABLE IF NOT EXISTS perfiles_estudiante (
    id_perfil BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL UNIQUE,
    rsh_porcentaje INTEGER,
    nem_promedio NUMERIC(3,1),
    id_region BIGINT,
    id_institucion BIGINT,
    carrera_interes VARCHAR(255),
    es_primer_anio BOOLEAN NOT NULL DEFAULT FALSE,
    es_curso_superior BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_pe_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_pe_region
        FOREIGN KEY (id_region) REFERENCES regiones(id_region) ON DELETE SET NULL,
    CONSTRAINT fk_pe_institucion
        FOREIGN KEY (id_institucion) REFERENCES instituciones(id_institucion)
        ON DELETE SET NULL
);

-- =============================================
-- Tabla: becas_favoritas (relacion M:N Usuario-Beca)
-- =============================================
CREATE TABLE IF NOT EXISTS becas_favoritas (
    id_usuario BIGINT NOT NULL,
    id_beca BIGINT NOT NULL,
    PRIMARY KEY (id_usuario, id_beca),
    CONSTRAINT fk_bf_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_bf_beca
        FOREIGN KEY (id_beca) REFERENCES becas(id_beca) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bf_usuario
    ON becas_favoritas(id_usuario);

CREATE INDEX IF NOT EXISTS idx_bf_beca
    ON becas_favoritas(id_beca);

-- =============================================
-- Datos semilla: roles
-- =============================================
INSERT INTO roles (nombre_rol)
VALUES ('ADMIN'), ('USER')
ON CONFLICT (nombre_rol) DO NOTHING;

-- =============================================
-- Datos semilla: tipos de institucion
-- =============================================
INSERT INTO tipos_institucion (nombre)
SELECT datos.nombre
FROM (
    VALUES
        ('Universidad'),
        ('Instituto Profesional'),
        ('Centro de Formación Técnica'),
        ('Fundación'),
        ('Organismo Gubernamental'),
        ('Empresa Privada'),
        ('ONG'),
        ('Municipal')
) AS datos(nombre)
WHERE NOT EXISTS (
    SELECT 1
    FROM tipos_institucion existente
    WHERE existente.nombre = datos.nombre
);

-- =============================================
-- Datos semilla: tipos de beca
-- =============================================
INSERT INTO tipos_beca (nombre)
SELECT datos.nombre
FROM (
    VALUES
        ('Beca de Arancel'),
        ('Beca de Mantención'),
        ('Beca de Alimentación'),
        ('Beca de Movilidad'),
        ('Beca de Investigación'),
        ('Beca de Excelencia Académica'),
        ('Beca Deportiva'),
        ('Beca Cultural')
) AS datos(nombre)
WHERE NOT EXISTS (
    SELECT 1
    FROM tipos_beca existente
    WHERE existente.nombre = datos.nombre
);

-- =============================================
-- Datos semilla: regiones de Chile
-- =============================================
INSERT INTO regiones (nombre, abreviatura)
SELECT datos.nombre, datos.abreviatura
FROM (
    VALUES
        ('Arica y Parinacota', 'XV'),
        ('Tarapacá', 'I'),
        ('Antofagasta', 'II'),
        ('Atacama', 'III'),
        ('Coquimbo', 'IV'),
        ('Valparaíso', 'V'),
        ('Metropolitana de Santiago', 'RM'),
        ('O''Higgins', 'VI'),
        ('Maule', 'VII'),
        ('Ñuble', 'XVI'),
        ('Biobío', 'VIII'),
        ('La Araucanía', 'IX'),
        ('Los Ríos', 'XIV'),
        ('Los Lagos', 'X'),
        ('Aysén', 'XI'),
        ('Magallanes', 'XII')
) AS datos(nombre, abreviatura)
WHERE NOT EXISTS (
    SELECT 1
    FROM regiones existente
    WHERE existente.nombre = datos.nombre
       OR existente.abreviatura = datos.abreviatura
);

COMMIT;
